[package]
name = "fpx-workers"
version = "0.1.0"
edition = "2021"
authors = ["Benno van den Berg <bennovandenberg@gmail.com>"]

[package.metadata.release]
release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = { version = "0.7", default-features = false }
console_error_panic_hook = { version = "0.1.1" }
tower-service = "0.3.2"
worker = { version = "0.2.0", features = ['http', 'axum'] }
worker-macros = { version = "0.2.0", features = ['http'] }
